#library "myproject"

// Tell NewTid what is the first tid it may use:
#define TIDALLOCSTART 15000

// Your project's script numbers.
#define myproject_errorhandler 701

// Tell ACSUtils which script to send errors to:
#define ACSUTILS_ERROR_HANDLER myproject_errorhandler

// Includes.
#include "zcommon.acs"
#include "acsutils.acs"

// Your project's error handler
script myproject_errorhandler (int type, int message)
{
	Log(s:"error: ", s:message);
	printbold(s:"error: ", s:message);
}
