#library "myproject"

// Your project's scripts:
#define myproject_errorhandler 701

// ACSUtils settings:
#define TIDALLOCSTART 15000
#define ACSUTILS_ERROR_HANDLER myproject_errorhandler

// Includes:
#include "zcommon.acs"
#include "acsutils.acs"

// Your project's error handler:
script myproject_errorhandler (int type, int message)
{
	Log(s:"error: ", s:message);
	printbold(s:"error: ", s:message);
}

// Your project's code follows.