@const fixed HUDTIC = 0.03;
@const fixed HUD_STAYTIME_FOREVER = fixed(-1);

@const int HUD_BLENDSTYLE_NORMAL = 0;
@const int HUD_BLENDSTYLE_ADDITIVE = 1;

@const int HUD_ALIGN_CENTER = 0;
@const int HUD_ALIGN_LEFT = 1;
@const int HUD_ALIGN_RIGHT = 2;
@const int HUD_ALIGN_TOP = 1;
@const int HUD_ALIGN_BOTTOM = 2;

@const int HUD_PROJECTION_AUTO = 0;
@const int HUD_PROJECTION_3D = 1;
@const int HUD_PROJECTION_YSHEARING = 2;
